SAS-113 Переделал Invite с использованием ConfirmToken.
GrabovskyAlexey/StAlSer pull request #107
Opened 2023-03-01 22:03 UTC by Kingl88

2023-03-02 07:15 UTC, GrabovskyAlexey requested changes

2023-03-02 07:15 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
> +        if (invite.getStatus().equals(InviteStatus.EXPIRED) || invite.getExpirationDate().isBefore(Instant.now())) {
Это можно не проверять, у нас же в токене время жизни зашито, можно оставить только проверку статуса, и лучше наверное проверить что статус не SENTтогда бросать исключение, чтобы исключить повторную обработку токенов, у нас токен должен обрабатыватся только когда он не был обработан раньше

2023-03-02 07:15 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
> +            throw new InviteTokenException("Тип токена не является приглашением (TokenType.INVITE)");
лучше не отдавать на фронт внутренние данные типа TokenType.INVITE фронт о них знать не знает и пользователю не следует

2023-03-02 07:15 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
>          if (!user.getEmail().equals(invite.getEmail())) {
можно еще проверить что почта в токене тоже соответствует почте в инвайте или у пользователя если уж совсем обезопасится

2023-03-02 09:20 UTC, GrabovskyAlexey approved these changes

2023-03-03 16:15 UTC, grafwwwolf approved these changes

2023-03-03 16:15 UTC, merged