Sas 2
GrabovskyAlexey/StAlSer pull request #11
Opened 2023-01-26 18:33 UTC by grafwwwolf

Создать сервиса со стандартными CRUD операциями

2023-01-26 18:44 UTC, GrabovskyAlexey requested changes

2023-01-26 18:44 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/BoardServiceImpl.java
> +        return boardRepository.findById(id);
Имеет смысл из Optional в сервисе доставать и сразу кидать исключение если сущность не найдена

2023-01-26 18:44 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/BoardServiceImpl.java
> +        Board board = findById(boardDto.getId()).orElse(new Board());
Не стоит создавать новую борду если она не найдена, лучше кидать 404 или 400, и я mapStruct подключил для маппинга. Опять же вопрос где маппить, если в сервисе тогда из методов на поиск следует тоже сразу ДТОшками возвращать, либо мапить в контроллерах тогда сюда передавать сущность, думаю это надо обговорить

2023-01-26 18:44 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/BoardServiceImpl.java
> +        save(board);
Думаю лучше через репозиторий сохранять, более очевидный код будет

2023-01-27 17:05 UTC, GrabovskyAlexey requested changes

2023-01-27 17:05 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/BoardServiceImpl.java
> +
Название метода не соответствует сути, у тебя же теперь не ДТО передается

2023-01-27 17:05 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/BoardServiceImpl.java
> +        board.setIsActive(boardDto.getIsActive());
Смысла искать и мапить нет если ты уже энтитю в метод передаешь, если только проверить что у нее есть id, если id нет то это новая сущность и через апдейт она сохраниться а это не корректно

2023-01-27 17:05 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/interfaces/BoardService.java
> +    @Transactional
транзакшнал здесь по идее не нужен если не искать энтитю

2023-01-27 17:14 UTC, grafwwwolf commented on core/src/main/java/ru/gb/stalser/core/services/BoardServiceImpl.java
> +
так это сервис. Будут ДТО, будем передавать сюда ДТО

2023-01-27 17:15 UTC, grafwwwolf commented on core/src/main/java/ru/gb/stalser/core/services/BoardServiceImpl.java
> +        board.setIsActive(boardDto.getIsActive());
тут то же, в сервис будем ДТО принимать

2023-01-27 17:47 UTC, GrabovskyAlexey approved these changes

2023-01-27 17:48 UTC, Kingl88 approved these changes

2023-01-27 17:49 UTC, merged