Sas 28
GrabovskyAlexey/StAlSer pull request #41
Opened 2023-02-01 16:43 UTC by grafwwwolf

SAS-28 Создание контроллера для авторизации пользователей с генерацией JWT токена

2023-02-01 17:57 UTC, celean77777 commented on api/src/main/java/ru/gb/stalser/api/dto/sprint/SprintDto.java
> +    private Long board;
это уже исправлено в sas_14_new

2023-02-01 17:58 UTC, celean77777 commented on core/src/main/java/ru/gb/stalser/core/mappers/SprintMapper.java
> +public interface SprintMapper {
исправлено в SAS_14_NEW

2023-02-02 09:39 UTC, GrabovskyAlexey requested changes

2023-02-02 09:39 UTC, GrabovskyAlexey commented on api/src/main/java/ru/gb/stalser/api/dto/auth/AuthRequest.java
> +public class AuthRequest {
забыл swagger аннотации

2023-02-02 09:39 UTC, GrabovskyAlexey commented on api/src/main/java/ru/gb/stalser/api/dto/auth/AuthResponse.java
> +public class AuthResponse {
и здесь забыл swagger аннотации

2023-02-02 09:39 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/controllers/AuthControllerImpl.java
> +@RequestMapping("/${stalser.api.url}/auth")
мне кажется лучше для эндпоинтов регистрации и авторизации путь делать просто /auth без api  и версии

2023-02-02 09:39 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/controllers/interfaces/AuthController.java
> +            summary = "Authenticate",
Лучше на русском

2023-02-02 09:39 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/controllers/interfaces/AuthController.java
> +                    @ApiResponse(responseCode = "200", description = "Successfully authenticate", content = {
И здесь тоже лучше на русском

2023-02-02 09:39 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/controllers/AuthControllerImpl.java
> +    public ResponseEntity<?> createAuthToken(@RequestBody AuthRequest authRequest) {
Лучше поставить сверху аннотацию @Override чтобы было понятно что метод переопределен

2023-02-02 09:39 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/controllers/AuthControllerImpl.java
> +            return new ResponseEntity<>(new MessageDto("Incorrect login or password"), HttpStatus.UNAUTHORIZED);
Возможно стоит создать перехватчик исключений и уже в нем обрабатывать BadCredentialsException,тогда мы сможем более четко параметризировать возвращаемый тип в методе как ResponseEntity<AuthResponse>

2023-02-02 17:49 UTC, GrabovskyAlexey approved these changes

2023-02-02 18:14 UTC, Kingl88 approved these changes

2023-02-02 18:15 UTC, merged