SAS-36. Доработка сервиса приглашений.
GrabovskyAlexey/StAlSer pull request #49
Opened 2023-02-04 20:53 UTC by Kingl88

Доработать сервис приглашений для проверки что пользователь уже зарегистрирован и тогда просто прикрепить его к борде.

2023-02-05 07:28 UTC, GrabovskyAlexey requested changes

2023-02-05 07:28 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
> +            invite.setUser(null);
Здесь эксепшн может вылететь и отловится если не найдена борда

2023-02-05 07:28 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
> +            user = userService.findByEmail(invite.getEmail());
Лучше добавить в репо и сервис метод по проверке есть ли такой пользователь, и сначала проверить, если его нет тогда налл присваивать, если есть тогда получать пользователя по емейлу

2023-02-05 18:37 UTC, GrabovskyAlexey requested changes

2023-02-05 18:37 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/UserServiceImpl.java
> +                () -> new NullPointerException("User id=" + id + "{} not found"));
а зачем здесь NPE выбрасывать? EntityNotFoundException здесь вполне подходил

2023-02-05 18:37 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
> +        User user;
Лучше сразу инициализировать null и тогда можно избавится от блока else при проверке пользователя

2023-02-05 18:37 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
> +            throw new RuntimeException(e.getMessage());
Здесь лучше какой то кастомный эксепшн сделать а не рантайм

2023-02-05 19:12 UTC, GrabovskyAlexey approved these changes

2023-02-06 12:21 UTC, LowBob93 approved these changes

2023-02-06 12:21 UTC, merged