Sas 34. Доработать сервис приглашений для передачи данных в кафку для отправки пользователю
GrabovskyAlexey/StAlSer pull request #53
Opened 2023-02-07 10:14 UTC by Kingl88

2023-02-07 10:31 UTC, GrabovskyAlexey requested changes

2023-02-07 10:31 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/config/KafkaConfig.java
> +    AuthenticationManager authenticationManager(AuthenticationConfiguration authenticationConfiguration) throws Exception { // создаем бин AuthenticationManager
А зачем здесь authenticationManager? на это у Стаса отдельная задача есть

2023-02-07 10:31 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/config/KafkaConfig.java
> +    public BCryptPasswordEncoder passwordEncoder() {//подключаем функцию для шифрования
А зачем здесь passwordEncoder? на это у Стаса отдельная задача есть

2023-02-07 10:31 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
> +        if (boardService.existsBoardById(invite.getBoard().getId())) {
Слишком много вложенных ифов, лучше  в этом ифе инвертировать условие и если доски нет сразу кинуть исключение а если доска есть то после Ифа сразу получить ее имя и сохранить в переменную чтобы при подготовке сообщения было более лаконичное заполнение subject

2023-02-07 10:31 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
> +                message = SimpleTextEmailMessage.builder()
Слишком много дублирующегося кода, возможно стоит собирать сначала SimpleTextEmailMessage без текста, а потом через сеттер добавлять текст в зависимости от того есть ли пользователь или нет

2023-02-07 10:31 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
> +                kafkaTemplate.send("simple-text-email", message);
И отправку делать 1 раз после того как полностью соберем сообщение

2023-02-07 10:31 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
> +                        .subject("Приглашение на добавление на доску " + boardService.findById(invite.getBoard().getId()).getBoardName())
Если заранее дергать имя доски то тут можно будет написать более читабельно например
"Приглашение на добавление на доску " + boardName

2023-02-07 10:31 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/config/KafkaTopicConfig.java
> +}
а точно ли этот конфиг нужен? Помоему KafkaConfig вполне достаточно из без этого конфига будет работать.

2023-02-07 10:50 UTC, Kingl88 commented on core/src/main/java/ru/gb/stalser/core/config/KafkaTopicConfig.java
> +}
Без этого кафка не запускается, возможно это можно настроить в проперти файле или даже в компоуз файле... надо пробовать.

2023-02-07 11:15 UTC, GrabovskyAlexey requested changes

2023-02-07 11:15 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/config/KafkaTopicConfig.java
> +}
Я пока апрувить не буду, вечером подолью себе твою ветку, поиграюсь, посмотрю, просто я когда для теста почты делал у меня у меня кафка топика не было и все нормально работало

2023-02-07 11:15 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
> +                .from("no-reply@stalser.com")
надо подумать о том чтобы вынести адрес отправки в проперти, добавь пожалуйста тут TODO об этом чтобы потом не забыть

2023-02-07 19:42 UTC, GrabovskyAlexey approved these changes

2023-02-08 17:59 UTC, grafwwwolf approved these changes

2023-02-08 17:59 UTC, merged