апдейт таблицы boadrs
GrabovskyAlexey/StAlSer pull request #6
Opened 2023-01-25 20:42 UTC by grafwwwolf

в таблицу boadrs добавить колонки board_alias(алиас доски), creator_id(id пользователя, создавшего доску), is_active

2023-01-25 20:49 UTC, GrabovskyAlexey commented on core/src/main/resources/db/migration/V2__update_boards_table.sql
> +ADD COLUMN IF NOT EXISTS creator_id bigserial,
bigint надо, bigserial инкрементится

2023-01-26 06:56 UTC, GrabovskyAlexey requested changes

2023-01-26 06:56 UTC, GrabovskyAlexey commented on core/src/main/resources/db/migration/V2__update_boards_table.sql
> +ADD CONSTRAINT fk_board_creator_id FOREIGN KEY (creator_id) REFERENCES users (id);
За внешний ключ респект )

2023-01-26 17:03 UTC, GrabovskyAlexey approved these changes

2023-01-27 09:44 UTC, Kingl88 approved these changes

2023-01-27 09:44 UTC, merged