SAS-35. Доработал сервис для принятия приглашения.
GrabovskyAlexey/StAlSer pull request #61
Opened 2023-02-09 11:29 UTC by Kingl88

2023-02-09 15:16 UTC, GrabovskyAlexey requested changes

2023-02-09 15:16 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
> +        User user = invite.getUser();
А если это инвайт новому пользователю который не зарегистрирован? тут будет null

2023-02-09 15:16 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/InviteServiceImpl.java
> +        User user = invite.getUser();
и неплохо бы проверять соответствует почта в инвайте почте пользователя, а то вдруг кто то чужой инвайт будет активировать

2023-02-09 18:47 UTC, GrabovskyAlexey requested changes

2023-02-09 18:47 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/exceptions/handlers/GlobalExceptionHandler.java
> +    public ResponseEntity<MessageDto> catchResourceNotFoundException(InviteWasExpiredException e) {
лучше в названии метода тоже использовать тип перехватываемого исключения

2023-02-09 18:47 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/exceptions/handlers/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(new MessageDto(e.getMessage()), HttpStatus.NOT_FOUND);
а почему статус 404, что мы не нашли? возможно тут тоже стоит 400 код отсылать, и можно тогда оба метода объединить в один и назвать его как-нибудь типа catchInviteExceptions

2023-02-09 19:21 UTC, GrabovskyAlexey approved these changes

2023-02-10 18:11 UTC, LowBob93 approved these changes

2023-02-10 18:11 UTC, merged