SAS-20
GrabovskyAlexey/StAlSer pull request #67
Opened 2023-02-11 16:13 UTC by RancidRabbit

добавлена TagDto и контроллер для работы с Tag entity

2023-02-11 16:30 UTC, GrabovskyAlexey requested changes

2023-02-11 16:30 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/controllers/interfaces/TagController.java
> +            @Parameter(name = "id", description = "Tag id", required = true) @PathVariable("id") Long id
только идентификатора не достаточно для того чтобы обновить тег, нужна еще информация о том что мы обновляем

2023-02-11 16:30 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/controllers/TagControllerImpl.java
> +        tagService.update(Optional.of(tagService.findById(id))
А разве метод апдейт тег сервиса принимает в себя опшнал?

2023-02-12 11:23 UTC, GrabovskyAlexey approved these changes

2023-02-12 17:54 UTC, grafwwwolf approved these changes

2023-02-12 17:54 UTC, merged