Создание сервиса для активностей
GrabovskyAlexey/StAlSer pull request #7
Opened 2023-01-25 21:09 UTC by Kingl88

Создал сервис для активностей

2023-01-26 16:31 UTC, GrabovskyAlexey requested changes

2023-01-26 16:31 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/ActivityServiceImpl.java
> +        return activityRepository.findById(id);
Думаю лучше в сервисе уже из Optional достать и проверить наличие, и при отсутствии кинуть исключение

2023-01-26 16:31 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/ActivityServiceImpl.java
> +        return null;
Потерял реализацию

2023-01-27 06:16 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/ActivityServiceImpl.java
> +        return activityRepository.findById(id).orElseThrow(()->new ResourceNotFoundException("Activity id = " + id + " not found"));
более понятным будет исключение EntityNotFoundException

2023-01-27 06:24 UTC, GrabovskyAlexey approved these changes

2023-01-27 17:27 UTC, grafwwwolf commented on core/src/main/java/ru/gb/stalser/core/entity/Activity.java
> +    private LocalDateTime createdAt;
договаривались, что тип будет Instant, и аннотация @CreationTimestamp

2023-01-27 17:27 UTC, grafwwwolf commented on core/src/main/java/ru/gb/stalser/core/entity/Activity.java
> +    private LocalDateTime updatedAt;
тип Instant, и аннотация @UpdateTimestamp

2023-01-27 17:53 UTC, grafwwwolf approved these changes

2023-01-27 17:53 UTC, merged