SAS-64. Заполнение таблицы задачи, доски, пользователи.
GrabovskyAlexey/StAlSer pull request #75
Opened 2023-02-13 22:14 UTC by Kingl88

2023-02-14 07:37 UTC, GrabovskyAlexey requested changes

2023-02-14 07:37 UTC, GrabovskyAlexey commented on core/src/main/resources/db/migration/V5__insert_data.sql
> +values ('Ivan@gmail.com', 'Ivan', '$2a$12$7FXCEUFEMFYip9dhrA.MEeFXDo9ZzwtGk1q7Todqmnpupjk73a32C'),
лучше не gmail использовать а либо example.com или какие то свои личные ящики, а то когда у нас начнут нотификации работать люди с этими ящиками явно не обрадуются )

2023-02-14 07:37 UTC, GrabovskyAlexey commented on core/src/main/resources/db/migration/V5__insert_data.sql
> +VALUES ('Проект1', 'Тестовый проект', 'test1', 1),
board_desc лучше различным делать, пусть и так же с нумерацией

2023-02-14 12:05 UTC, GrabovskyAlexey requested changes

2023-02-14 12:05 UTC, GrabovskyAlexey commented on core/src/main/resources/db/migration/V5__insert_data.sql
> +       (4, 'Задача 4', 'Описание задача 4', 'CLOSE', 'TRIVIAL', 'NEW_FEATURE', '2023-03-01', 7, 1),
Замени пожалуйста везде NEW_FEATURE на просто FEATURE, я когда enum со статусами задач делал задублировал статус, по сути это одно и то же

2023-02-14 12:22 UTC, GrabovskyAlexey approved these changes

2023-02-16 15:45 UTC, LowBob93 approved these changes

2023-02-16 15:46 UTC, merged