SAS-53 Добавлен Principal в контроллеры
GrabovskyAlexey/StAlSer pull request #78
Opened 2023-02-15 18:15 UTC by LowBob93

2023-02-15 20:50 UTC, GrabovskyAlexey requested changes

2023-02-15 20:50 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/controllers/interfaces/UserController.java
> +            @Parameter(name = "AuthRequest", description = "AuthRequest Item", required = true) @Valid @RequestBody AuthRequest authRequest, Principal principal
в юзер контроллере принципал не нужен, у нас его тупо еще не будет при регистрации и аутентификации

2023-02-16 07:47 UTC, GrabovskyAlexey requested changes

2023-02-16 07:47 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/controllers/ActivityControllerImpl.java
> +    public ResponseEntity<ActivityDto> getActivityById(Long id,Principal principal) {
Пробел после запятой забыл, пройдись по всем файлам контроллеров с Ctrl+Alt+L

2023-02-16 07:47 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/controllers/UserControllerImpl.java
> +
А зачем здесь 2 дополнительных перевода строки?

2023-02-16 14:03 UTC, GrabovskyAlexey approved these changes

2023-02-16 21:59 UTC, Kingl88 approved these changes

2023-02-16 21:59 UTC, merged