Добавлена сущность и репозиторий на Comment
GrabovskyAlexey/StAlSer pull request #8
Opened 2023-01-26 16:00 UTC by LowBob93

2023-01-26 16:17 UTC, GrabovskyAlexey requested changes

2023-01-26 16:17 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/entity/Comment.java
> +@Data
Data переопределяет equals и hashCode по всем полям, лучше убрать Data и сделать с геттерами и сеттерами, идея сама подсказывает как ее можно заменить

2023-01-26 16:17 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/entity/Comment.java
> +    @Column(name = "created_at")
Не хватает аннотации @CreationTimestamp

2023-01-26 16:17 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/repositories/CommentRepository.java
> +    // List<Comment>findAllByCommentText(String commentText);
Не очень хорошая практика оставлять в коде закомментированные куски кода, репозиторий пока можно спокойно оставить вообще пустым

2023-01-26 18:16 UTC, GrabovskyAlexey approved these changes

2023-01-27 09:42 UTC, Kingl88 approved these changes

2023-01-27 09:42 UTC, merged