SAS-65
GrabovskyAlexey/StAlSer pull request #82
Opened 2023-02-16 21:11 UTC by celean77777

SAS-65

2023-02-17 06:41 UTC, GrabovskyAlexey requested changes

2023-02-17 06:41 UTC, GrabovskyAlexey commented on api/src/main/java/ru/gb/stalser/api/dto/auth/AuthRequestPassUpdate.java
> +    private String login;
если пользователь меняет свой пароль то может стоит вместо логина его айдишник передавать? поиск по базе по айдишнику будет быстрее чем по логину

2023-02-17 06:41 UTC, GrabovskyAlexey commented on api/src/main/java/ru/gb/stalser/api/dto/auth/AuthRequestPassUpdate.java
> +    private String login;
Или даже ничего не передавать, этот эндпоинт должен быть под аутентификацией и мы пользователя из Principal сможем дернуть

2023-02-17 06:41 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/controllers/UserControllerImpl.java
> +    public ResponseEntity<AuthResponse> registerUpdate (@RequestBody AuthRequestPassUpdate authRequestPassUpdate){
может лучше метод назвать changePassword, все таки обновление регистрации не такое говорящее о том что в методе происходит

2023-02-17 06:41 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/controllers/interfaces/UserController.java
> +            path = {"/register/update"}
эндпоинт думаю стоит назвать /password/change

2023-02-17 06:41 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/UserServiceImpl.java
> +import ru.gb.stalser.core.services.repositories.UserRepository;
а почему репозиторий в сервисы уехал?

2023-02-17 06:41 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/UserServiceImpl.java
> +            authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(authRequestPassUpdate.getLogin(), authRequestPassUpdate.getOldPassword()));
не очень хороший вариант, мы если что выкинем BadCredentialException а нам надо проверить всего лишь совпадает пароль в БД с паролем присланным, возможно стоит дергать пользователя из базы и у BCryptPasswordEncoder есть метод позволяющий проверить соответствие захешированного пароля и не хешированного, и при несовпадении какое то свое исключение кидать

2023-02-17 06:41 UTC, GrabovskyAlexey commented on api/src/main/java/ru/gb/stalser/api/dto/auth/AuthRequestPassUpdate.java
> +    private String newPassword;
Неплохо бы поля паролей сваггером аннотировать, с ограничением по длине

2023-02-19 15:15 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/UserServiceImpl.java
> +        if(bCryptPasswordEncoder.matches(authRequestPassUpdate.getOldPassword(), user.getPassword())){
Здесь всегда будет NPE потому что Principal не инстанс юзера, пропиши просто что метод принимает Principal principal остальное туда просунет Spring Security, из юзера берешь логин и по логину и через репозиторий уже получаешь юзера

2023-02-19 15:15 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/UserServiceImpl.java
> +           return new AuthResponse(String.format("Пароль пользователя '%s' не подтвержден", user.getLogin()));
тут лучше выбросить какое-нибудь исключение и перехватить его в глобальном обработчике чтобы не возвращать статус ответа что все прошло без ошибок

2023-02-19 15:15 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/controllers/interfaces/UserController.java
> +    @ResponseStatus(HttpStatus.CREATED)
Статус created означает что мы создали какой то объект, луче убрать и тогда в случае успеха будет возвращаться просто ОК(200)

2023-02-19 16:01 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/services/UserServiceImpl.java
> +    public AuthResponse registerPassUpdate(AuthRequestPassUpdate authRequestPassUpdate) throws NullPointerException{
не стоит указывать что ты пробрасываешь НПЕ на верх, во-первых это RuntimeException и его не обязательно указывать в инструкции throws а во вторых если ты знаешь что у тебя есть НПЕ его необходимо сразу корректно обработать

2023-02-19 17:47 UTC, GrabovskyAlexey approved these changes

2023-02-19 17:50 UTC, Kingl88 approved these changes

2023-02-20 15:20 UTC, merged