Sas 1
GrabovskyAlexey/StAlSer pull request #9
Opened 2023-01-26 17:33 UTC by grafwwwolf

Созданы сущности и репозиторий для досок

2023-01-26 17:36 UTC, GrabovskyAlexey requested changes

2023-01-26 17:36 UTC, GrabovskyAlexey commented on core/src/main/java/ru/gb/stalser/core/entity/Board.java
> +    private Long creatorId;
Тут надо на юзера ссылаться

2023-01-27 17:40 UTC, Kingl88 approved these changes

2023-01-27 17:46 UTC, GrabovskyAlexey approved these changes

2023-01-27 17:47 UTC, merged